import { widget } from '../factory'
export const Navbar = widget('nav', { class: 'lumine-navbar' })
export const Sidebar = widget('aside', { class: 'lumine-sidebar' })
export const SidebarItem = widget('a', { class: 'lumine-sidebar-item' })
export const Tabs = widget('div', { class: 'lumine-tabs' })
export const TabList = widget('div', { class: 'lumine-tab-list', role: 'tablist' })
export const Tab = widget('button', { class: 'lumine-tab', role: 'tab', type: 'button' })
export const TabPanel = widget('div', { class: 'lumine-tab-panel', role: 'tabpanel' })
export const Breadcrumb = widget('nav', { class: 'lumine-breadcrumb', 'aria-label': 'Breadcrumb' })
export const BreadcrumbItem = widget('a', { class: 'lumine-breadcrumb-item' })
export const Pagination = widget('nav', { class: 'lumine-pagination', 'aria-label': 'Pagination' })
export const Stepper = widget('ol', { class: 'lumine-stepper' })
export const Step = widget('li', { class: 'lumine-step' })
export const Link = widget('a', { class: 'lumine-link' })
