import { widget } from '../factory'
export const Alert = widget('div', { class: 'lemine-alert', role: 'alert' })
export const Toast = widget('div', { class: 'lemine-toast', role: 'status' })
export const Modal = widget('div', { class: 'lemine-modal', role: 'dialog' })
export const ModalHeader = widget('header', { class: 'lemine-modal-header' })
export const ModalBody = widget('div', { class: 'lemine-modal-body' })
export const ModalFooter = widget('footer', { class: 'lemine-modal-footer' })
export const Drawer = widget('aside', { class: 'lemine-drawer' })
export const DrawerHeader = widget('header', { class: 'lemine-drawer-header' })
export const DrawerBody = widget('div', { class: 'lemine-drawer-body' })
export const DrawerFooter = widget('footer', { class: 'lemine-drawer-footer' })
export const Tooltip = widget('div', { class: 'lemine-tooltip', role: 'tooltip' })
export const Popover = widget('div', { class: 'lemine-popover' })
export const Progress = widget('progress', { class: 'lemine-progress' })
export const Skeleton = widget('div', { class: 'lemine-skeleton', 'aria-hidden': true })
export const ContextMenu = widget('div', { class: 'lemine-context-menu', role: 'menu' })
