import { widget } from '../factory'
export const Alert = widget('div', { class: 'lumine-alert', role: 'alert' })
export const Toast = widget('div', { class: 'lumine-toast', role: 'status' })
export const Modal = widget('div', { class: 'lumine-modal', role: 'dialog' })
export const ModalHeader = widget('header', { class: 'lumine-modal-header' })
export const ModalBody = widget('div', { class: 'lumine-modal-body' })
export const ModalFooter = widget('footer', { class: 'lumine-modal-footer' })
export const Drawer = widget('aside', { class: 'lumine-drawer' })
export const DrawerHeader = widget('header', { class: 'lumine-drawer-header' })
export const DrawerBody = widget('div', { class: 'lumine-drawer-body' })
export const DrawerFooter = widget('footer', { class: 'lumine-drawer-footer' })
export const Tooltip = widget('div', { class: 'lumine-tooltip', role: 'tooltip' })
export const Popover = widget('div', { class: 'lumine-popover' })
export const Progress = widget('progress', { class: 'lumine-progress' })
export const Skeleton = widget('div', { class: 'lumine-skeleton', 'aria-hidden': true })
export const ContextMenu = widget('div', { class: 'lumine-context-menu', role: 'menu' })
